name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '13 2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.unitedutilities.com/help-and-support/your-water-supply/your-reservoirs/reservoir-levels/ > reservoir-levels.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
